service: notes-api

# Create an optimized package for our functions
package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
